-- ============================================================
-- IBEW Aptitude Test Prep — Database Schema
-- Target: Supabase (PostgreSQL)
-- ============================================================
-- auth.users is managed by Supabase Auth — do not create it manually.
--
-- NOTE: this file is hand-maintained documentation, not a migration runner.
-- The live database is authoritative. If you change the DB, change this too.
-- (There are no migrations checked in; adding supabase/migrations/ would stop
-- this file drifting again.)

-- 1. USER PROFILES
-- Extended info beyond what Supabase Auth stores.
-- Created immediately after account registration.
-- ============================================================
CREATE TABLE user_profiles (
  id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  desired_score   SMALLINT CHECK (desired_score BETWEEN 1 AND 9),
  local_union     TEXT,       -- e.g. "Local 81 – Scranton, PA" (optional)
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. TEST SESSIONS
-- UNIQUE on user_id enforces the one-attempt-per-account rule.
-- ============================================================
CREATE TABLE test_sessions (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  test_id             TEXT NOT NULL DEFAULT 'practice-test-1',
  status              TEXT NOT NULL DEFAULT 'in_progress'
                        CHECK (status IN ('in_progress', 'completed', 'abandoned')),
  started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at        TIMESTAMPTZ,
  time_spent_seconds  INTEGER,       -- total wall-clock time, set on completion
  math_raw            SMALLINT,      -- 0–35 correct
  reading_raw         SMALLINT,      -- 0–36 correct
  composite_score     NUMERIC(3,1)   -- 1.0–9.0, computed on submission
);

-- ============================================================
-- 3. QUESTION RESPONSES
-- One row per question per session.
-- answer_chosen is NULL if the question was skipped.
-- ============================================================
CREATE TABLE question_responses (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id          UUID NOT NULL REFERENCES test_sessions(id) ON DELETE CASCADE,
  question_id         TEXT NOT NULL,          -- e.g. "m001", "r023"
  section             TEXT NOT NULL CHECK (section IN ('math', 'reading')),
  answer_chosen       CHAR(1) CHECK (answer_chosen IN ('A','B','C','D')),
  is_correct          BOOLEAN,
  time_spent_seconds  INTEGER NOT NULL DEFAULT 0,
  flagged_for_review  BOOLEAN NOT NULL DEFAULT FALSE,
  answered_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (session_id, question_id)
);

-- ============================================================
-- 4. DIAGNOSTIC REPORTS
-- Computed server-side on session completion and stored so the
-- dashboard loads instantly without recomputing.
-- Written by the server using the service role — clients can
-- only SELECT their own report (see RLS below).
-- ============================================================
CREATE TABLE diagnostic_reports (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id        UUID NOT NULL UNIQUE REFERENCES test_sessions(id) ON DELETE CASCADE,
  user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Per-skill breakdown
  -- Shape: { "algebraic_substitution": { "correct": 3, "total": 5, "pct": 0.6 }, ... }
  skill_scores      JSONB NOT NULL DEFAULT '{}',

  -- Ordered study plan (generated by scoring.ts)
  -- Shape: [{ skill, category, hours_estimate, reason, chain? }, ...]
  -- category: "quick_win" | "foundation" | "prerequisite_chain" | "stretch"
  study_plan        JSONB NOT NULL DEFAULT '[]',

  -- Summary numbers shown at top of dashboard
  score_gap         SMALLINT,      -- desired_score - composite_score (negative = already at goal)
  hours_to_passing  NUMERIC(4,1),  -- estimated hours to reach score 4
  hours_to_goal     NUMERIC(4,1),  -- estimated hours to reach desired_score

  -- Skills where a prerequisite is also weak (highlighted in dashboard)
  -- Shape: [{ "skill": "linear_equations", "weak_prereqs": ["fractions"] }, ...]
  prerequisite_gaps JSONB NOT NULL DEFAULT '[]',

  -- Warm 2-3 sentence note generated by Claude on submission (may be null if
  -- the AI call fails; submission is never blocked on it).
  ai_summary        TEXT
);

-- ============================================================
-- 5. WAITLIST
-- Emails captured on the results page for future study material.
-- Anonymous-friendly: written server-side with the service role.
-- ============================================================
CREATE TABLE waitlist (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 6. ISSUE REPORTS
-- User-submitted bug reports. The user types only a message; the app
-- attaches context. Written server-side with the service role so that
-- anonymous visitors on the marketing pages can report too.
-- ============================================================
CREATE TABLE issue_reports (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  message     TEXT NOT NULL CHECK (char_length(btrim(message)) BETWEEN 1 AND 2000),

  -- Attribution is derived server-side from the session, never trusted
  -- from the client. SET NULL, not CASCADE: a retake deletes the
  -- test_session, and losing the report that prompted it would be backwards.
  user_id     UUID REFERENCES auth.users(id)    ON DELETE SET NULL,
  session_id  UUID REFERENCES test_sessions(id) ON DELETE SET NULL,

  -- Auto-captured context
  path        TEXT,
  question_id TEXT,
  phase       TEXT,
  section     TEXT,
  viewport    TEXT,   -- e.g. "375x812"
  user_agent  TEXT,
  app_version TEXT,   -- VERCEL_GIT_COMMIT_SHA

  status      TEXT NOT NULL DEFAULT 'new'
                CHECK (status IN ('new', 'triaged', 'resolved'))
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_responses_session   ON question_responses(session_id);
CREATE INDEX idx_reports_user        ON diagnostic_reports(user_id);
CREATE INDEX idx_issue_reports_created ON issue_reports(created_at DESC);
CREATE INDEX idx_issue_reports_user    ON issue_reports(user_id);

-- ============================================================
-- ROW LEVEL SECURITY
-- Users can only access their own data.
-- ============================================================
ALTER TABLE user_profiles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_sessions      ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE diagnostic_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own profile"
  ON user_profiles FOR ALL USING (auth.uid() = id);

CREATE POLICY "own session"
  ON test_sessions FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "own responses"
  ON question_responses FOR ALL
  USING (session_id IN (SELECT id FROM test_sessions WHERE user_id = auth.uid()));

-- Reports are written server-side (service role); clients only read.
CREATE POLICY "own report read"
  ON diagnostic_reports FOR SELECT USING (auth.uid() = user_id);

-- waitlist and issue_reports are service-role only. RLS is enabled with NO
-- policies, which denies anon and authenticated entirely. Nothing in the app
-- reads either table back — triage happens in the Supabase dashboard.
ALTER TABLE waitlist       ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_reports  ENABLE ROW LEVEL SECURITY;
